# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# Site settings
baseurl: "" # the subpath of your site, e.g. /blog

description: > # this means to ignore newlines until the next tag
  Learn practical and advanced techniques in software development and
  devops from the engineering and operations staff of RentPath. The infrastructure
  at RentPath is almost entirely open source, and mobile and web applications are developed
  in Objective C, Java, JavaScript, Ruby, and Clojure. This blog provides hands-on examples,
  reviews of technology, best practices, key learnings, insights, and staff profiles.

email: blog@rentpath.com

gems:
  - jekyll-feed

github_username:  rentpath

title: The RentPath Development and DevOps blog

twitter_username: rentpathdevs

url: "http://yourdomain.com" # the base hostname & protocol for your site


#
# Build settings
exclude:
  - README.md
  - bin
  - tmp
  - vendor

markdown: kramdown
